# Generated by Django 5.1.4 on 2025-01-06 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_lesson_url"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_pay",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата платежа"
                    ),
                ),
                (
                    "amount_pay",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Сумма оплаты"
                    ),
                ),
                (
                    "way_pay",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Наличные", "Наличные"),
                            ("Перевод на счет", "Перевод на счет"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_course",
                        to="lms.course",
                        verbose_name="Оплаченный курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
