# Generated by Django 5.1.4 on 2025-01-22 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_lesson_course"),
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="lms.course",
                verbose_name="Курс",
            ),
        ),
    ]
