# Generated by Django 5.1.4 on 2025-01-06 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="date_pay",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="Дата платежа",
            ),
            preserve_default=False,
        ),
    ]
