# Generated by Django 5.1.4 on 2025-01-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите Id продукта",
                max_length=255,
                null=True,
                verbose_name="Id продукта",
            ),
        ),
    ]
