# Generated by Django 5.1.4 on 2025-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Активность"
            ),
        ),
    ]
